version: "3.3"
services:
  states:
    build: ./states-api
    ports:
      - "3030:3030"
    volumes:
      - .:/code
  population:
    build: ./population-api
    ports:
      - "3031:3031"
    volumes:
      - .:/code
